name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch API Data
        run: |
          curl -s https://alfa-leetcode-api.onrender.com/NaitikVerma > data.json

      - name: Extract Values
        run: |
          EASY=$(jq '.easySolved' data.json)
          MEDIUM=$(jq '.mediumSolved' data.json)
          HARD=$(jq '.hardSolved' data.json)
          TOTAL=$(jq '.totalSolved' data.json)
          RANK=$(jq '.ranking' data.json)
          CONTRI=$(jq '.contributionPoint' data.json)

          echo "EASY=$EASY" >> $GITHUB_ENV
          echo "MEDIUM=$MEDIUM" >> $GITHUB_ENV
          echo "HARD=$HARD" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "RANK=$RANK" >> $GITHUB_ENV
          echo "CONTRI=$CONTRI" >> $GITHUB_ENV

      - name: Update LeetCode Section
        run: |
          START="<!-- LEETCODE-START -->"
          END="<!-- LEETCODE-END -->"

          awk -v start="$START" -v end="$END" \
              -v easy="$EASY" \
              -v medium="$MEDIUM" \
              -v hard="$HARD" \
              -v total="$TOTAL" \
              -v rank="$RANK" \
              -v contri="$CONTRI" '
          BEGIN {flag=0}
          $0 ~ start {
            print start
            print ""
            print "## <img src=\"https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/leetcode.svg\" width=\"25\"/> LeetCode Stats"
            print ""
            print "| 📊 Category | 🚀 Stats |"
            print "|------------|--------|"
            print "| 🟢 Easy | " easy " |"
            print "| 🟡 Medium | " medium " |"
            print "| 🔴 Hard | " hard " |"
            print "| 📌 Total | " total " |"
            print "| 🏆 Rank | " rank " |"
            print "| 🔥 Contribution | " contri " |"
            print ""
            flag=1
            next
          }
          $0 ~ end {
            print end
            flag=0
            next
          }
          !flag { print }
          ' README.md > temp && mv temp README.md

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Updated LeetCode stats" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
